[package]
name = "germinate"
version = "0.1.0"
authors = ["Iain Earl <iain@itmecho.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.30"
async-trait = "0.1.31"
rusoto_core = "0.43.0"
rusoto_ssm = "0.43.0"
regex = "1.3.7"
# TODO check if we can use a subset of features
tokio = { version = "0.2.21", features = ["full"] }
rusoto_mock = "0.43.0"
