on:
  push:
    tags:
      - '*'

name: CI

jobs:
  # Create GitHub release with Rust build targets and release notes
  github_release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Create GitHub Release
    needs: github_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # These can be squashed when https://github.com/actions/download-artifact/issues/6 is closed
      - name: Download releases from github_build
        uses: actions/download-artifact@v1
        with:
          name: germinate-x86_64-unknown-linux-gnu.tar.gz
          path: .
      - name: Download releases from github_build
        uses: actions/download-artifact@v1
        with:
          name: germinate-x86_64-unknown-linux-musl.tar.gz
          path: .
      - name: Download releases from github_build
        uses: actions/download-artifact@v1
        with:
          name: germinate-x86_64-apple-darwin.tar.gz
          path: .

      - name: Generate checksums
        run: for file in germinate-*; do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done

      - name: Create GitHub release ${{ matrix.target }}
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            germinate-x86_64-unknown-linux-gnu.tar.gz
            germinate-x86_64-unknown-linux-gnu.tar.gz.sha256
            germinate-x86_64-unknown-linux-musl.tar.gz
            germinate-x86_64-unknown-linux-musl.tar.gz.sha256
            germinate-x86_64-apple-darwin.tar.gz
            germinate-x86_64-apple-darwin.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
